theme: minima
title: teste novo blog 3
author: asotack
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Este é apenas um teste to aprendendo a usar isso

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
